### ISSUE TITLE
Formulario de inscripción. Rubro debería de ser un combobox

### ISSUE THREAD

**Issue by danicricco** [Asepy/fishswarm-frontend#13]
### Descripción
En el formulario de inscripción se pide llenar el campo "rubro". Se espera que el campo sea un dropdown con valores que pueden venir desde el servidor.

## Definición de hecho
* El campo rubro es un dropdown
* El campo rubro se carga con valores que provienen de un endpoint.

**Comment by rodrigojv** [comment]
Se puede seleccionar de un listado que viene del back o bien especificar un rubro en un input.

**Comment by danicricco** [comment]
Genial ! Gracias.
