### ISSUE TITLE
Formulario de inscripción. Socio Plus V1

### ISSUE THREAD

**Issue by danicricco** [Asepy/fishswarm-frontend#15]
## Descripción

El formulario de inscripción de socio debería tener la opción de ser socio Plus. Esto lo vamos a plantear en dos etapas:
* A futuro: El socio plus se va a poder autogestionar el pago (esto no es para este ticket).
* Ahora: Necesitamos que marque su voluntad de ser socio plus.

La idea es que el formulario posea la capacidad de marcar que querés ser socio Plus y te van a contactar telefónicamente para realizar la gestión. 

## Como implementar en el formulario?

Debería ser una sección que se habilité (o no) con un check box que diga: ¿Querés ser socio Plus?
Esta sección debe tener una breve descripción de lo que significar ser socio Plus. Ejemplo:
"Los socios Plus aportan 100.000 Gs mensuales. Esto permite que ASEPY pueda sostener su operación y colaborar en que Paraguay sea un mejor ecosistema para emprender. Marcando estos datos, una persona de nuestro equipo se pondrá en contacto contigo para coordinar."

A modo de referencia, en el formulario actual está
![image](https://user-images.githubusercontent.com/3456558/118519301-fef3a800-b706-11eb-9759-aecbc6bc39c2.png)

De estos campos, necesitamos:
* Modalidad de pago.
* Dirección de facturación.

## Definición de hecho
* El formulario de inscripción posee la sección de socio Plus
* La sección de socio plus se des/habilita de acuerdo al checkbox.

**Comment by rodrigojv** [comment]
Se puede registrar marcando una opción de "Quiero ser Socio Plus" y luego eso registra al socio con el estado "Plus Pendiente" en el backoffice y con la opción de Cambiar Estado se puede asignarle la membresía de "Socio Plus".

**Comment by danicricco** [comment]
Gracias R! quedó muy purete el diseño
