### ISSUE TITLE
Como backofficer, puedo ver los campos claves en la tabla de búsqueda

### ISSUE THREAD

**Issue by danicricco** [Asepy/fishswarm-frontend#19]
## Descripción
Como Backofficer al realizar la búsqueda se ven pocos campos en la tabla. El objetivo es mostrar los siguientes:
* Departamento
* Ciudad
* CI
* Nombre
* Apellido
* RUC
* Razón Social

## Definición de hecho
* La tabla de backoffice muestra las columnas mencionadas como resultado de la búsqueda.

**Comment by rodrigojv** [comment]
Se agregaron los campos que faltaban con excepción de Razón Social que hasta ahora no lo hemos definido como clave.

**Comment by danicricco** [comment]
Que purete que quedó el Departamento debajo de la ciudad!

Fernando de la Mora
CENTRAL
