### ISSUE TITLE
Como BackOfficer, me gustaría tener un botón "buscar" para accionar la busqueda

### ISSUE THREAD

**Issue by danicricco** [Asepy/fishswarm-frontend#26]
### Descripción
Actualmente el Backofficer no posee un botón buscar, lo cual resulta en una dificultad para disparar la búsqueda.

Si bien funciona el "enter" al querer realizar una busqueda por estado, no resulta claro como dispararla.

![image](https://user-images.githubusercontent.com/3456558/119259642-2af6a980-bb9d-11eb-99fd-9e47b96f0b80.png)

Por otro lado, el botón "limpiar" parece no ser muy útil.

## Definición de hecho
* En lugar del botón "limpiar" se posee un botón de "buscar".
* El botón de buscar lanza la búsqueda.

**Comment by rodrigojv** [comment]
Se agrega el botón de Buscar pero se mantiene el de Limpiar, salvo que no se considere estrictamente necesario.
