### ISSUE TITLE
Evaluar opciones para registro en backoffice limitado a miembros de ASEPY

### ISSUE THREAD

**Issue by rodrigojv** [Asepy/fishswarm-frontend#41]
El registro de Backoffice es para cualquiera que tenga acceso al link. Evaluar una manera que solo sea para los miembros de asepy.

**Comment by rodrigojv** [comment]
Se quita la opción de crearte tu propia cuenta de backoffice.

Se van a registrar los usuarios desde la web de administración de Cognito Users (en el aws console).

Una vez que se registra un nuevo usuario se le asigna un password temporal, el cual se le envía automáticamente por e-mail al usuario interesado.

El usuario al acceder por primera vez con ese password temporal se le va a pedir que modifique su password. Esto es sólo la primera vez y a partir de ahi ya podrá loguearse con el password que el usuario seteó.

**Comment by danicricco** [comment]
Una belleza

**Comment by danicricco** [comment]
Purete !
