### ISSUE TITLE
Tener 2 instancias del front-end. Uno apuntando a /Prod y otro a /Dev.

### ISSUE THREAD

**Issue by danicricco** [Asepy/fishswarm-frontend#48]

**Comment by rodrigojv** [comment]
Se actualizó el readme con las urls a ambas instancias.

<img width="506" alt="Screen Shot 2021-08-06 at 11 49 04" src="https://user-images.githubusercontent.com/17142306/128537337-e977b7f0-8da4-4f23-9cbc-4ce65692ce44.png">

Las urls bajo el título de Urls Desarrollo apuntan al front/back de desarrollo.

Las otras url son de producción.
